### ISSUE TITLE
One file missing

### ISSUE THREAD

**Issue by swangek2002** [Thanksyy/LineNet-and-LineBench-SIGMOD2023#1]
I have run this project in my laptop. But it said that this code seems to be missing a file named `names_dtai.npy`.
![Snipaste_2023-10-05_17-47-04](https://github.com/Thanksyy/LineNet-and-LineBench-SIGMOD2023/assets/110212385/fa409e95-826e-4939-a0de-7d1c0867f408)

**Comment by Thanksyy** [comment]
Sorry:)  You can modify the config.py to set the TRAIN.LOAD_MAP parameter to True. Once the data is preprocessed, you can set this parameter to False. Thanks for pointing this out, I will update the README soon.
